name: sdk

on:
  push:
    branches:
      - master
    paths:
      - 'platform.*'
      - 'builder/**'
      - 'examples/sdk/**'
      - '**/sdk.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "hal-blink"
          - "ll-blink"
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          submodules: "recursive"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/pio/archive/main.zip
          pio platform install file://.

      - name: build sdk
        working-directory: examples/sdk
        run: |
          pio run -d ${{ matrix.example }}
